on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Build the project
        run: cmake --build build

      - name: Test the project
        run: ./build/test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-result
          path: |
            ./build/hello
            ./build/test

      - name: Copy production artifact to Petr's server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PETR_HOST }}
          username: ${{ secrets.PETR_USERNAME }}
          key: ${{ secrets.PETR_PRIVATE_KEY }}
          source: "./build/hello"
          target: "/srv/wishlist_amir/bin"
          strip_components: 2

      - name: Executing remote ssh commands on Petr's server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PETR_HOST }}
          username: ${{ secrets.PETR_USERNAME }}
          key: ${{ secrets.PETR_PRIVATE_KEY }}
          script: |
            mv /srv/wishlist_amir/bin/hello /srv/wishlist_amir/bin/wishlist
            sudo systemctl restart wishlist

      - name: Copy production artifact to my server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./build/hello"
          target: "/srv/wishlist/bin"
          overwrite: true
          strip_components: 2

      - name: Executing remote ssh commands on my server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mv /srv/wishlist/bin/hello /srv/wishlist/bin/wishlist
            sudo systemctl restart wishlist
